### ISSUE TITLE
Question about gradient calculation during full batch training

### ISSUE THREAD

**Issue by sbite0138** [JonasGeiping/fullbatchtraining#3]
Thank you for sharing your implementation. I have a question about the gradient calculation during full batch training.

 If I understand correctly, I believe the calculation of gradients during full batch training is achieved by dividing dataset into mini-batches and calculating gradients for each of them, and then taking the average.

 I think the implementation of calculating the gradients for each mini-batch and taking the average is on [lines 142-169 of training.py](https://github.com/JonasGeiping/fullbatchtraining/blob/main/fullbatch/training/training.py#L142-L169).
 However, I'm not quite sure what the purpose of the line 165
https://github.com/JonasGeiping/fullbatchtraining/blob/acec6cb2045e8fe526e1d42f08995b8a4920700e/fullbatch/training/training.py#L165
is. 
As far as I understand, I think that this line is unnecessary because `average_grads` can be simply the average for each `grads` (and it's done on line 166).
If there's anything I'm misunderstanding, could you please let me know?

**Comment by JonasGeiping** [comment]
Hi, this line is also part of the mean computation. What's happening here is a numerically stable mean computation. 

This is part of Welford's algorithm, but there is also a blog post here discussing it specifically for mean computations: https://diego.assencio.com/?index=c34d06f4f4de2375658ed41f70177d59.

Given that many samples are averaged, I wanted the mean calculation to be as precise as possible, especially for the 10x-40x CIFAR scenarios with up to 2mil data points.

**Comment by JonasGeiping** [comment]
Yeah, Welford's algorithm requires a moving counter. I haven't looked at this code in a while and maybe I am forgetting a caveat, but at least right now, I think this is indeed a bug: the loop should run over `block` and `idx` and not over `num_blocks * chunks_in_block`. 

From a cursory derivation this seems to accumulate error terms that scale with $\frac{1}{N^p}, p \in [1, N]$, for $N$ the total number of samples. These are probably vanishing for large $N$, but still, this appears to be an incorrect mean.

**Comment by JonasGeiping** [comment]
Hi, thanks for doing the calculation in detail.

To keep you in the loop, I've fixed the computation on a new branch (`correctedmean`) and I am currently testing if anything changes as a result of this fix.

**Comment by JonasGeiping** [comment]
So far, I can't find a systematic difference between both versions, I've merged the new branch into main now.

**Comment by JonasGeiping** [comment]
Don't hesitate to let me know if something else comes up, closing this for now!
