### ISSUE TITLE
Error when trying to run the script

### ISSUE THREAD

**Issue by Changhao-Xu** [JonasGeiping/fullbatchtraining#4]
Hi! I installed this repository and tried to run the model, but when I typed in cmd the training runs:
python train_with_gradient_descent.py name=fbaug_gradreg_lr08 hyp=gradreg
The following error will pop up: " Error executing job with overrides: ['name=fbaug_gradreg_lr08', 'hyp=gradreg'] "

Could you please help so that I could reproduce your result? Many thanks in advance!

![Error message](https://user-images.githubusercontent.com/60868518/224910748-c9afcdd4-60e3-4e73-8774-97099f31fca0.png)

**Comment by JonasGeiping** [comment]
Your OS appears to windows or macOS. Please set `impl.setup.strategy` to a multiprocessing sharing strategy that works for your OS, probably `file_system`.

**Comment by Changhao-Xu** [comment]
Thank you so much for your help! It is working now. Really appreciate it!
